import { ColumnDef } from "@tanstack/react-table";
import { fuzzySort } from "../sorter/fuzzySort";

export const productListColumns: ColumnDef<any, any>[] = [
  {
    accessorFn: (row) => row.category,
    id: "category",
    header: "카테고리",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.title,
    id: "title",
    header: "타이틀",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.artist,
    id: "artist",
    header: "가수",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.price,
    id: "price",
    header: "가격",
    // enableColumnFilter: false,
    cell: (info) => info.getValue(),
    // filterFn: "fuzzy",
    // sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.ent,
    id: "ent",
    header: "소속사",
    // enableColumnFilter: false,
    cell: (info) => info.getValue(),
    // filterFn: "fuzzy",
    // sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.barcode,
    id: "barcode",
    header: "바코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.sku,
    id: "sku",
    header: "SKU",
    cell: (info) => `${info.getValue()}`,
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.releaseDate,
    id: "releaseDate",
    header: "출시일",
    cell: (info) => info.getValue()?.substr(0, 10),
    // filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.preorderDeadline,
    id: "preorderDeadline",
    header: "주문마감",
    cell: (info) => info.getValue()?.substr(0, 10),
    // filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
];
